/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaprogram;


import java.sql.ResultSet;
import javax.swing.*;
import java.sql.*;
import javax.swing.AbstractListModel;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javaprogram.DatabaseDriver;
import javaprogram.ADDC;
import javaprogram.ADDP;
import javaprogram.DELC;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;
import model.categories;
import model.ListTableModel;


/**
 *
 * 
 */
public class ProgramUI extends javax.swing.JFrame {

    /**
     * Creates new form ProgramUI
     */
    public ProgramUI() throws SQLException {
       
        this.BAZADANYCH = new DatabaseDriver();
        this.ADDCWind = new ADDC();
        this.gcatdata = new Vector<categories>();
        BAZADANYCH.selectALLProducts();
        result = BAZADANYCH.stat.executeQuery("SELECT productID, productName AS Name,productPrice AS Price,purchasePlace AS 'Purchase Place',purchaseDate AS 'Purchase Date',"
                + "expiryDate AS 'Expiry Date',productWarranty AS 'Product Warranty',categories.categoryName AS Category FROM product inner join categories on categories.categoryID = product.categoryID");
        mod = ListTableModel.createModelFromResultSet(result);
        this.Center = new DefaultTableCellRenderer();
        Center.setHorizontalAlignment(SwingConstants.CENTER);
        initComponents();
        for(int i = 0;i < this.jTable1.getColumnCount();i++)
        {
            this.jTable1.getColumnModel().getColumn(i).setCellRenderer(Center);
        }
       this.jTable1.removeColumn(this.jTable1.getColumnModel().getColumn(0));
    }
    
    public DatabaseDriver BAZADANYCH;
    private ResultSet result;
    public ADDC ADDCWind;
    public ADDP ADDPWind;
    public DELP DELPWind;
    public DELC DELCWind;
    public UPP UPPWind;
    private TableModel model;
    public Vector<categories> gcatdata;
    private ListTableModel mod;
    private Statement stat;
    private DefaultTableCellRenderer Center;
    
  
    
    /**sdad
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        programLog = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("jMenu8");

        jMenu9.setText("jMenu9");

        jMenu10.setText("File");
        jMenuBar4.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar4.add(jMenu11);

        jMenu12.setText("jMenu12");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 433));

        jTable1.setModel(this.mod);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jMenu3.setText("File");

        jMenu5.setText("Add");

        jMenuItem1.setText("Category");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Product");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenu3.add(jMenu5);

        jMenu4.setText("Delete");

        jMenuItem3.setText("Category");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Product");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteProductAction(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenu3.add(jMenu4);

        jMenuBar2.add(jMenu3);

        jMenu14.setText("Sort");

        jMenuItem6.setText("By Category");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem6);

        jMenuItem7.setText("By Name");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem7);

        jMenuBar2.add(jMenu14);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(488, 488, 488)
                .addComponent(programLog, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(programLog, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            this.DELCWind = new DELC(this.jTable1);
            this.DELCWind.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ProgramUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void DeleteProductAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteProductAction
     
        try {
            this.DELPWind = new DELP(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(ProgramUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            this.DELPWind.setVisible(true);
            
        
    }//GEN-LAST:event_DeleteProductAction

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        
       this.ADDCWind.setVisible(true);
      
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            this.ADDPWind = new ADDP(jTable1);
            this.ADDPWind.setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(ProgramUI.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try {
            result = BAZADANYCH.stat.executeQuery("SELECT productID, productName AS Name,productPrice AS Price,purchasePlace AS 'Purchase Place',purchaseDate AS 'Purchase Date',"
                    + "expiryDate AS 'Expiry Date',productWarranty AS 'Product Warranty',categories.categoryName AS Category FROM product inner join categories on categories.categoryID = product.categoryID ORDER BY categories.categoryName");
            this.model = ListTableModel.createModelFromResultSet(result);
            this.jTable1.setModel(model);
            for(int i = 0;i < this.jTable1.getColumnCount();i++)
        {
          this.jTable1.getColumnModel().getColumn(i).setCellRenderer(Center);
        }
         this.jTable1.removeColumn(this.jTable1.getColumnModel().getColumn(0));
        } catch (SQLException ex) {
            Logger.getLogger(ProgramUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try {
            result = BAZADANYCH.stat.executeQuery("SELECT productID, productName AS Name,productPrice AS Price,purchasePlace AS 'Purchase Place',purchaseDate AS 'Purchase Date',"
                    + "expiryDate AS 'Expiry Date',productWarranty AS 'Product Warranty',categories.categoryName AS Category FROM product inner join categories on categories.categoryID = product.categoryID ORDER BY productName");
            this.model = ListTableModel.createModelFromResultSet(result);
            this.jTable1.setModel(model);
            for(int i = 0;i < this.jTable1.getColumnCount();i++)
        {
          this.jTable1.getColumnModel().getColumn(i).setCellRenderer(Center);
        }
        this.jTable1.removeColumn(this.jTable1.getColumnModel().getColumn(0));
        } catch (SQLException ex) {
            Logger.getLogger(ProgramUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if(evt.getClickCount() == 2)
        {
            System.out.println((int)this.jTable1.getModel().getValueAt(this.jTable1.getSelectedRow(), 0));
            try {
                this.UPPWind = new UPP(this.jTable1, (int) this.jTable1.getModel().getValueAt(this.jTable1.getSelectedRow(), 0));
                this.UPPWind.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(ProgramUI.class.getName()).log(Level.SEVERE, null, ex);
       }
        }
    }//GEN-LAST:event_jTable1MouseClicked
                
    
    
    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) throws SQLException {
        System.out.println("Hello!");
        
        
        
    
         
       
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    new ProgramUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ProgramUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JLabel programLog;
    // End of variables declaration//GEN-END:variables
}
