/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaprogram;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.categories;
import javaprogram.*;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import model.ListTableModel;
/**
 *
 * @author Danniel
 */
public class UPP extends javax.swing.JFrame {

    /**
     * Creates new form ADDP
     */
    public UPP(JTable arg, int ID) throws SQLException {
        this.Nazwycat = new Vector<String>();
        this.baza = new DatabaseDriver();
        this.data = new Vector<categories>();
        tablica = arg;
        int i = 0;
        this.Center = new DefaultTableCellRenderer();
        Center.setHorizontalAlignment(SwingConstants.CENTER);
        this.data = this.baza.SelectALLCategories();
       this.result = this.baza.stat.executeQuery("SELECT * FROM PRODUCT WHERE productID = " + ID);
        this.id = ID;
      for(categories temp : data)
       {
            this.Nazwycat.addElement(temp.CN);
           
            i++;
       }
        initComponents();
        while(result.next())
       {
     this.CategoryChoose.setSelectedItem(this.tablica.getModel().getValueAt(this.tablica.getSelectedRow(), 7));
    this.PNcontainer.setText(this.result.getString("productName"));
    this.Pricecontainer.setText(this.result.getString("productPrice"));
    this.PlaceContainer.setText(this.result.getString("purchasePlace"));
    this.DateContainer.setText(this.result.getString("purchaseDate"));
    this.ExpireContainer.setText(this.result.getString("expiryDate"));
    this.WarrantyContainer.setText(this.result.getString("productWarranty")); 
       }
    }

    
    
    
    public DatabaseDriver baza;
    public Vector<String> Nazwycat;
    public Vector<categories> data;
    private static JTable tablica;
    private ListTableModel model;
    private DefaultTableCellRenderer Center;
    public static int id;
    public static int categoryID;
     ResultSet result;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CategoryChoose = new javax.swing.JComboBox();
        PNcontainer = new javax.swing.JTextField();
        Pricecontainer = new javax.swing.JTextField();
        PlaceContainer = new javax.swing.JTextField();
        DateContainer = new javax.swing.JTextField();
        ExpireContainer = new javax.swing.JTextField();
        WarrantyContainer = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        UPPPRODUCTBUTTON = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        CategoryChoose.setModel(new javax.swing.DefaultComboBoxModel(this.Nazwycat));
        CategoryChoose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CategoryChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryChooseActionPerformed(evt);
            }
        });

        PNcontainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNcontainerActionPerformed(evt);
            }
        });

        Pricecontainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PricecontainerActionPerformed(evt);
            }
        });

        PlaceContainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceContainerActionPerformed(evt);
            }
        });

        ExpireContainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpireContainerActionPerformed(evt);
            }
        });

        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        UPPPRODUCTBUTTON.setText("UPDATE");
        UPPPRODUCTBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPPPRODUCTBUTTONActionPerformed(evt);
            }
        });

        jLabel1.setText("Category");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setText("Product Name");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel3.setText("Product Price");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel4.setText("Purchase Place");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel5.setText("Purchase Date");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel6.setText("Expire Date");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel7.setText("Product Warranty");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 161, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UPPPRODUCTBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ExpireContainer, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DateContainer, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PlaceContainer, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Pricecontainer, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PNcontainer, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CategoryChoose, javax.swing.GroupLayout.Alignment.LEADING, 0, 143, Short.MAX_VALUE)
                                    .addComponent(WarrantyContainer))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PNcontainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pricecontainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlaceContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpireContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WarrantyContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(UPPPRODUCTBUTTON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PNcontainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNcontainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PNcontainerActionPerformed

    private void PricecontainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PricecontainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PricecontainerActionPerformed

    private void PlaceContainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaceContainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlaceContainerActionPerformed

    private void CategoryChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryChooseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoryChooseActionPerformed

    
    private void UPPPRODUCTBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPPPRODUCTBUTTONActionPerformed
    int categoryID;
    categoryID = this.data.get(this.CategoryChoose.getSelectedIndex()).ID;
        try {
           this.baza.stat.execute("UPDATE product SET productName = '" + this.PNcontainer.getText() + "', "
            + "productPrice = '" + this.Pricecontainer.getText() + "', "
            + "purchasePlace = '" + this.PlaceContainer.getText() + "', "
                   + "purchaseDate = '" + this.DateContainer.getText() + "', "
                   + "expiryDate = '" + this.ExpireContainer.getText() +"', "
                   + "productWarranty = '" + this.WarrantyContainer.getText() + "',"
                   + "categoryID = " + categoryID + " WHERE productID = " + this.id);
          result = baza.stat.executeQuery("SELECT productID, productName AS Name,productPrice AS Price,purchasePlace AS 'Purchase Place',purchaseDate AS 'Purchase Date',"
                + "expiryDate AS 'Expiry Date',productWarranty AS 'Product Warranty',categories.categoryName AS Category FROM product inner join categories on categories.categoryID = product.categoryID");
            this.model = ListTableModel.createModelFromResultSet(result);
        } catch (SQLException ex) {
            Logger.getLogger(UPP.class.getName()).log(Level.SEVERE, null, ex);
        }
        tablica.setModel(model);
        for(int i = 0;i < this.tablica.getColumnCount();i++)
        {
            this.tablica.getColumnModel().getColumn(i).setCellRenderer(Center);
        }
     this.tablica.removeColumn(this.tablica.getColumnModel().getColumn(0));
     this.dispose();
    }//GEN-LAST:event_UPPPRODUCTBUTTONActionPerformed

    private void ExpireContainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpireContainerActionPerformed

    }//GEN-LAST:event_ExpireContainerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UPP(tablica,id).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(UPP.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox CategoryChoose;
    private javax.swing.JTextField DateContainer;
    private javax.swing.JTextField ExpireContainer;
    private javax.swing.JTextField PNcontainer;
    private javax.swing.JTextField PlaceContainer;
    private javax.swing.JTextField Pricecontainer;
    private javax.swing.JButton UPPPRODUCTBUTTON;
    private javax.swing.JTextField WarrantyContainer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
